on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Fetch data
        run: |
          curl -A "${{ secrets.USER_AGENT }}" https://www.dshield.org/api/intelfeed/?json | jq "." > intelfeed

      - name: Update cache
        run: |
          cat intelfeed | jq '[.[] | select( (.description | contains("blocklistde22") or contains("blocklistde80") or contains("blocklistde443") )) | .ip ] | unique | sort' > data.json
      
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Update data file
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -am "${{ env.CI_COMMIT_MESSAGE }} - ${{ github.head_ref }}.${{ github.sha }}" || exit 0
          git push
