on:
  push:
    branches:
      - main
    paths-ignore:
      - bad_actors.json
      - cloud_ips.json
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * *'

jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq
      
      - name: Fetch intelfeed
        run: |
          sleep 10
          curl -A "${{ secrets.USER_AGENT }}" https://www.dshield.org/api/intelfeed/?json | jq "." > intelfeed
          
      
      - name: Fetch coudcidrs
        run: |
          sleep 10
          curl -A "${{ secrets.USER_AGENT }}" https://isc.sans.edu/api/cloudcidrs?json | jq "." > cloudcidrs

      - name: Update cache
        run: |
          cat intelfeed | jq '[.[] | select( (.description | contains("blocklistde22") or contains("blocklistde80") or contains("blocklistde443") )) | .ip ] | unique | sort' | jq -r tostring | tee bad_actors.json | head -n 10

          cat cloudcidrs | jq "[ .[] | .prefix ]"  | tee cloud_ips.json | head -n 10
      
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Update data file(s)
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -am "${{ env.CI_COMMIT_MESSAGE }} - ${{ github.head_ref }}.${{ github.sha }}" || exit 0
          git push
