on:
  push:
    branches:
      - main
    paths-ignore:
      - bad_actors.json
      - cloud_ips.json
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'


env:
  POETRY_VERSION: 1.5.1
  PYTHON_VERSION: '3.10'


jobs:
  fetch_data:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: Install jq
        run: sudo apt-get install -y jq
      
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - uses: Gr1N/setup-poetry@v8
        with:
          poetry-version: ${{ env.POETRY_VERSION }}
      
      - name: Fetch intelfeed
        run: |
          sleep 10
          curl -A "${{ secrets.USER_AGENT }}" https://www.dshield.org/api/intelfeed/?json | jq "." | tee intelfeed | head -n 10
          
      
      - name: Fetch cloudcidrs
        run: |
          sleep 10
          curl -A "${{ secrets.USER_AGENT }}" https://isc.sans.edu/api/cloudcidrs?json | jq "." | tee cloudcidrs | head -n 10

      - name: Archive raw data
        uses: actions/upload-artifact@v3
        with:
          name: raw-data
          retention-days: 5
          path: |
            intelfeed
            cloudcidrs

      - name: Update cache
        run: |
          cat intelfeed | jq '[.[] | select( (.description | contains("blocklistde") or contains("miner") or contains("torexit") or contains("forumspam")  )) | .ip ] | unique | sort' | jq -r tostring | tee bad_actors.json | head -n 10

          cat cloudcidrs | jq "[ .[] | .prefix ]"  | tee cloud_ips.json | head -n 10
      
      - name: Update simplified lists
        env:
          USER_AGENT: ${{ secrets.USER_AGENT }}
        run: make
      
      - name: GIT commit and push all changed files
        env: 
          CI_COMMIT_MESSAGE: Update data file(s)
          CI_COMMIT_AUTHOR: Continuous Integration
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "username@users.noreply.github.com"
          git commit -am "Update data files - ${{ github.sha }}" || exit 0
          git push
